server:
  port: 8081

spring:
  application:
    name: demo app


logging:
  file: "target/demo-sample.log"


eureka:  #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone:  ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

